% autogenerated using generate_minimal_rules.ipynb

standard(Nieruchomosc, luksusowy) :-
    nieruchomosc_typ(Nieruchomosc, Typ),
    Typ = dom.


standard(Nieruchomosc, wysoki) :-
    nieruchomosc_typ(Nieruchomosc, Typ),
    nieruchomosc_lokalizacja(Nieruchomosc, Lokalizacja),
    Typ = mieszkanie,
    Lokalizacja = centrum.


standard(Nieruchomosc, niski) :-
    nieruchomosc_lokalizacja(Nieruchomosc, Lokalizacja),
    Lokalizacja = przedmiescia.


standard(Nieruchomosc, sredni) :-
    nieruchomosc_lokalizacja(Nieruchomosc, Lokalizacja),
    Lokalizacja = obrzeza.


