% autogenerated using generate_minimal_rules.ipynb

standard(Nieruchomosc, luksusowy) :-
    nieruchomosc_powierzchnia(Nieruchomosc, Powierzchnia),
    Powierzchnia >= 237.


standard(Nieruchomosc, wysoki) :-
    nieruchomosc_powierzchnia(Nieruchomosc, Powierzchnia),
    nieruchomosc_typ(Nieruchomosc, Typ),
    nieruchomosc_pokoje(Nieruchomosc, Pokoje),
    Typ = apartament,
    Pokoje >= 4,
    Powierzchnia >= 190.


standard(Nieruchomosc, niski) :-
    nieruchomosc_powierzchnia(Nieruchomosc, Powierzchnia),
    Powierzchnia =< 45.


standard(Nieruchomosc, sredni) :-
    nieruchomosc_powierzchnia(Nieruchomosc, Powierzchnia),
    nieruchomosc_pokoje(Nieruchomosc, Pokoje),
    Pokoje =< 2,
    Powierzchnia >= 207.


