name: LaTeX PDF Build

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: pdflatex
          args: "-shell-escape -interaction=nonstopmode"
          pre_compile: |
            pdflatex -draftmode -interaction=nonstopmode main.tex
          post_compile: |
            pdflatex -interaction=nonstopmode main.tex
          working_directory: docs

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          path: docs/main.pdf