:- use_module(library(record)).

:- record nieruchomosc(
    id,
    typ,
    lokalizacja,
    ulica,
    miasto,
    region,
    kod_pocztowy,
    kraj,
    lat,
    long,
    odleglosc,
    powierzchnia,
    standard,
    pokoje,
    lazienki,
    rok,
    konstrukcja,
    pietra,
    nr_pietra,
    winda,
    parking,
    typ_parking,
    umeblowane,
    ogrzewanie,
    energia,
    powodz,
    stan,
    opis,
    dostepnosc,
    ostatni_remont,
    utworzono,
    zaktualizowano
).

:- record oferta_sprzedazy(
    id,
    property_id,
    status,
    cena,
    negocjacja,
    cena_max,
    cena_min,
    data_wystawienia,
    data_wygasniecia,
    platnosc
).

:- record oferta_wynajmu(
    id,
    property_id,
    status,
    cena,
    koszty_dodatkowe,
    opis_kosztow,
    kaucja,
    negocjacja,
    cena_max,
    cena_min,
    data_wystawienia,
    data_wygasniecia,
    min_start,
    max_start,
    min_okres,
    max_okres,
    umowa,
    typ_najmu,
    lokatorzy,
    opis_lokatorow,
    preferowany_najemca,
    zwierzeta,
    polityka_zwierzat,
    opis,
    typ_wlasciciela
).
